/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Nunito Sans', 'sans-serif'],
      },
      colors: {
        primary: '#3b82f6',
        secondary: '#8b5cf6',
        accent: '#FFC844',
        navy: '#224059',
        dark: '#171717',
        'text-primary': '#1f2937',
        'text-secondary': '#374151',
        'text-muted': '#6b7280',
        'text-light-muted': '#94a3b8',
        'bg-white': '#ffffff',
        'bg-off-white': '#f8fafc',
        'bg-light-gray': '#f1f5f9',
        'bg-slate': '#e2e8f0',
      },
      borderRadius: {
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        'pill': '50px',
        'circle': '50%',
      },
      fontSize: {
        'hero': 'clamp(40px, 5vw, 80px)',
        'section': 'clamp(36px, 5vw, 56px)',
        'card-title': '24px',
        'body-large': '20px',
        'body': '16px',
        'small': '14px',
        'tiny': '12px',
      },
      lineHeight: {
        tight: '1.1',
        snug: '1.2',
        normal: '1.5',
        relaxed: '1.6',
        loose: '1.7',
      },
      letterSpacing: {
        tight: '-0.025em',
        normal: '0em',
        loose: '0.025em',
        looser: '0.05em',
      },
      backgroundImage: {
        'gradient-main': 'linear-gradient(40deg, #dff9fb, #ffffff)',
        'gradient-section': 'linear-gradient(180deg, #f8fafc 0%, #ffffff 100%)',
        'gradient-primary': 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)',
        'gradient-yellow': 'linear-gradient(135deg, #FFC844 0%, #ff9b44 100%)',
      },
    },
  },
  plugins: [],
};
